- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
fixes:
- lost precision for longs above 2^53
- and floats above 10k
Also contains  `test_gbq.py` clean up
> BUG: fix read_gbq lost numeric precision

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
> Improve gbq.py code coverage

- docs/source/contributing.rst
Closes #4
This is almost identical to the contributing guidelines at https://github.com/pandas-dev/pandas. I removed some content which may not be applicable to pandas-gbq.
> DOC: Add contributor guidelines

- CONTRIBUTING.md
Full contributing (and testing) instructions are included in the docs.
http://pandas-gbq.readthedocs.io/en/latest/contributing.html
I didn't find these docs https://github.com/pydata/pandas-gbq/issues/27 because I didn't expect them to be in the user documentation, and I'm used to looking for a `CONTRIBUTING` file.
By creating a `CONTRIBUTING.md` file, GitHub users will be more likely to
find them. See: https://github.com/blog/1184-contributing-guidelines
> DOC: link to contributing guide

- docs/source/contributing.rst
- pandas_gbq/tests/test_gbq.py
Load the credentials for integration tests from environment variables.
This will make it easier to run the integration tests locally. Also adds
instructions for running the integrations tests locally.
Closes #27.
> TST: Load integration test creds from env vars

- docs/source/changelog.rst
- pandas_gbq/gbq.py
The command line arguments were not correctly propagated, which do not allowed using flags as 
`--noauth_local_webserve`. This seems to fix the issue and now the flag is correctly passed downstream.
> fix: Propagate command line arguments

- .travis.yml
> TST: Run flake8 in Travis-CI python 2.7 build

- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
Fixes #57. This 2 line fix was originally part of @tswast's PR #39 but I'm going to transfer it here so that it's easier to capture the specific fix. PR #39 also has other reliability improvements to the integration testing which resolve intermittent failures. The changes in this PR fix the consistent failure `TypeError: 'NoneType' object is not iterable`.
> TST: Fix broken tests failing with 'NoneType' object is not iterable / module 'pandas.util.testing' has no attribute 'assertRaises'

- docs/source/changelog.rst
- docs/source/writing.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
Current behavior of `to_gbq` is fail if the schema of the new data is not equivalent to the current schema. However, this means that the load fails if the new data is missing columns that are present in the current schema. For instance, this may occur when the data source I am using to construct the dataframe only provides non-empty values. Rather than determining the current schema of the GBQ table and adding empty columns to my dataframe, I would like `to_gbq` to load my data if the columns in the dataframe are a subset of the current schema.
- Factoring a `schema` function out of `verify_schema` to support both `verify_schema` and  `schema_is_subset`
- `schema_is_subset` determines whether `local_schema` is a subset of `remote_schema`
- the append flag uses `schema_is_subset` rather …
> When appending to a table, load if the dataframe contains a subset of the existing schema

- .gitignore
- ci/requirements-2.7-0.19.2.pip
- ci/requirements-3.5-0.18.1.pip
- ci/requirements-3.6-0.20.1.pip
- ci/requirements-3.6-MASTER.pip
- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
- requirements.txt
- setup.py
Remove the use of oauth2client and use google-auth library, instead.
Rather than check for multiple versions of the libraries, use the
setup.py to specify compatible versions. I believe this is safe since
Pandas checks for the pandas_gbq package.
Since google-auth does not use the argparse module to override user
authentication flow settings, add a parameter to choose between the web
and console flow.
Closes https://github.com/pydata/pandas-gbq/issues/37.
> BUG: oauth2client deprecated, use google-auth instead.

- docs/source/contributing.rst
Includes conda install steps for dependencies.
Closes https://github.com/pydata/pandas-gbq/issues/63.
> DOC: Add development installation instructions

- docs/source/changelog.rst
- pandas_gbq/gbq.py
Hi,
After few years of BQ usage I've reached point where I need to report support case to Google BQ Team.
I've attached my iPython notebook with pandas gbq output, but they needed query Job IDs.
This is simple change to add them in read_gbq.
I'm not using to_gbq at all so I've not added verbose output for it when I implemented read_gbq some time ago. Today it is still not much verbose so I leaving things as they are.
> ENH: BQ Job Id in verbose output

- docs/source/changelog.rst
- pandas_gbq/gbq.py
Hi,
to keep up the momentum I'm sharing my fancy query price print outs.
Feel free to abandon this if you do not like it.
At RTBHOUSE we are using it with pleasure :)
Feature:
Query price is printed with ascii art font. Font gets larger as price increases.
Sample outputs
- below $0,1 (plain text)
```
Processed: 10.3 Gb
Price: 0.05 $
Retrieving results...
```
- between $0,1 - $0,5 (first level of ascii font)
```
Processed: 31.3 GB
Price: 
||_    __         __ 
(||    /  \    /| |_  
_||)   \__/.    | __) 
||
Retrieving results...
```
- between $0.5 - $1
```
__,--,_.     ___      ______   _____  
/       |    / _ \    |____  | | ____| 
|   (----`   | | | |       / /  | |__   
\   \       | | | |      / /   |___ \  
.----)   |      | |_| |  __ / /     ___) | 
|_    __/        \___/  (__)_/ …
```
> ENH: query price presentation (uses pyfiglet fonts)

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
pandas-gbq seems to wait for query results forever.
In rare cases, query does not finish long time (e.g. in 60 minutes) although the same query always finishes in few minutes.
I added timeout handling using configuration.query.timeoutMs.
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query
Example
```python
import pandas as pd
import pandas_gbq.gbq
try:
df = pd.read_gbq(query, project_id=xxx, configuration={
'query': {'timeoutMs': 40000}
})
print(df.head())
except pandas_gbq.gbq.QueryTimeout as e:
print(e)
pass
```
Output
```
Requesting query... ok.
Job ID: job_8OSgsu7nYKNYycnlgAB2_KWTGGk
Query running...
Elapsed 13.78 s. Waiting...
Elapsed 25.08 s. Waiting...
Elapsed 36.27 s. Waiting...
Query timeout: 40000 ms
```
> ENH: Add timeout support

- docs/source/changelog.rst
- pandas_gbq/gbq.py
Minor adjustments to the change log for #76.
> DOC: Update change log

- docs/source/changelog.rst
- docs/source/intro.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
Closes #41
This PR adds ability for users to choose the location where BigQuery user account credentials will be stored via the `credentials_path` parameter.
This PR also changes the location of the file `bigquery_credentials.dat` that contains the BigQuery user account credentials. Previously this file was saved in the current working directory. The credentials file will now be stored in an application-specific hidden user folder on the operating system. On windows, this path is specified in the `APPDATA` environment variable as defined [here](https://technet.microsoft.com/en-ca/library/cc749104(v=ws.10).aspx) which is typically `'C:\Documents and Settings\username\Application Data\pandas-gbq\'` . Otherwise, credentials will be stored in `'~/.config/pandas-gbq/'`. If the file …
> ENH: Save BigQuery account credentials in a hidden user folder

- docs/source/changelog.rst
- pandas_gbq/gbq.py
Before https://github.com/pydata/pandas-gbq/pull/25 goes in, which will mark version `0.3.0`, I think it would be smart to make a release with the bug fixes that have happened since `0.2.0`.
> Prepare for 0.2.1 release.

- .travis.yml
To avoid `CondaError: BlockingIOError`
Builds running on my fork at https://travis-ci.org/tswast/pandas-gbq/builds/319425014
Closes #98.
> BLD: Use quiet flag for conda commands.

- docs/source/changelog.rst
The actual change was done in #25, but I missed that #7 exists when I updated the changelog.
Closes #7
> DOC: link to issue 7 for to_gbq changes

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
As per @tswast's requests in https://github.com/pydata/pandas-gbq/issues/22 and https://github.com/pydata/pandas-gbq/issues/23, tests added to check that arrays and structs are successfully returned and named properly from a query.
While running tests, identified a bug with the type conversion in read_gbq (see below). Updated it so it only performs type conversion with the added condition that the returned field mode IS NOT `repeated`.
```
>>> import gbq
>>> query = """WITH t as (
...         SELECT "a" letter, 1 num
...         UNION ALL
...         SELECT "b" letter, 2 num
...         UNION ALL
...         SELECT "a" letter, 3 num)
...
...         select letter, array_agg(num order by num ASC) num_array
...         from t
...         group by letter"""
>>> df = gbq.read_gbq(query, …
```
> BUG: Fix bug in type conversion of arrays; add array and struct tests

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
Potential fix for https://github.com/pydata/pandas-gbq/issues/106
...but someone with better bytes / str understanding needs to review
> Encode before uploading

- pandas_gbq/gbq.py
- setup.py
Version 0.29.0 of `google-cloud-bigquery` deprecates `Client.list_dataset_tables()` in favor of `Client.list_tables()`.
Build running at https://travis-ci.org/tswast/pandas-gbq/builds/333856912
> Upgrade to 0.29.0 of google-cloud-bigquery

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
> ENH: Add table_schema parameter for user-defined BigQuery schema

- ci/requirements-3.5-0.18.1.pip
- docs/source/changelog.rst
- pandas_gbq/_load.py
- pandas_gbq/_schema.py
- pandas_gbq/gbq.py
- pandas_gbq/tests/test__load.py
- pandas_gbq/tests/test__schema.py
- pandas_gbq/tests/test_gbq.py
Fixes #116 and #96 by loading data in CSV chunks.
> BUG: Fix uploading of dataframes containing int64 and float64 columns

- pandas_gbq/gbq.py
Solved issue #119 
On 64-bit windows 10 the `int` values are cast into 32-bit integers for reasons given here
https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine
This leads to unhandled exceptions when handling values beyond 32-bit signed range
In Bigquery, int is always 64bit, so the solution is to specify the data type explicitly
> BUG: Explicitly use 64bit integers when converting from BQ types

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
This PR resolves the bug documented here: https://github.com/pydata/pandas-gbq/issues/123
Basically, the custom dtype handling we have to convert missing values to NaNs fails when the field in BigQuery is an array (that is, in repeated mode). We simply set the dtype to an object if it is an array.
Added a test to check for this in the future. All previous tests still pass. Can also verify the bug and that this fixes by running:
```
gbq.read_gbq("select [1.1,2.2,3.3]","project",dialect="standard")
```
@tswast @MtDersvan
> Fix array of floats bug

- pandas_gbq/tests/test_gbq.py
I don't think this test was passing for a while?
> fix test_parse test

- .stickler.yml
We've got this running in xarray, and it's pretty good - much nicer to get a PR comment before the travis fail. 
https://github.com/pydata/xarray/pull/1913
One question is whether we want it adding changes automatically, in addition to the standard PR comments. I thought it was good but others didn't, so we decided to turn it off there. I've enabled it here, but open-minded.
Someone with commit privileges needs to start it checking here: https://stickler-ci.com/repositories
> add @stickler-ci

- .gitignore
- ci/requirements-3.5-0.18.1.pip
- pandas_gbq/tests/test_gbq.py
Move towards more pytest idioms, reduce amount of code, reduce branching. This is a starter; still lots to do.
But can merge if ppl agree and keep making small improvments
> Better test structure

- .gitignore
- docs/source/conf.py
- pandas_gbq/_load.py
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
- scripts/merge-py.py
- setup.cfg
- setup.py
- versioneer.py
Ran `isort -y`
Not worth enforcing I think, but occasional clean-ups (marginally) helpful
> CLN: isort

- pandas_gbq/_load.py
- pandas_gbq/tests/test_gbq.py
Fixed a bug that all TIMESTAMP fileds become 00 secconds in BigQuery.
https://github.com/pydata/pandas-gbq/issues/69#issuecomment-366431134  mentions to same issue.
* before ( note: In this case, I intentionally puts same datetime.now() value. )
* after
> BUG: fixed a bug that all TIMESTAMP fileds become 00 secconds.

- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
The `to_gbp` function fails when there is a user-defined schema which is slightly different from the schema of DataFrame.
Traceback:
```
Traceback (most recent call last):
File "<stdin>", line 4, in <module>
File "pandas_gbq/gbq.py", line 979, in to_gbq
schema=table_schema)
File "pandas_gbq/gbq.py", line 569, in load_data
self.process_http_error(ex)
File "pandas_gbq/gbq.py", line 450, in process_http_error
raise GenericGBQException("Reason: {0}".format(ex))
pandas_gbq.gbq.GenericGBQException: Reason: 400 POST https://www.googleapis.com/upload/bigquery/v2/projects/aktech-labs/jobs?uploadType=resumable: Provided Schema does not match Table aktech-labs:pandas_test.gamma. Field A has changed type from FLOAT to STRING
```
The primary reason for this is that the `load_data` function ignores the …
> Load data with user defined schema

- AUTHORS.md
- ci/requirements-3.5-0.18.1.pip
- setup.py
Closes https://github.com/pydata/pandas-gbq/issues/73
> bump google auth version

- .travis.yml
- ci/requirements-3.5-0.18.1.pip
- ci/requirements-3.6-MASTER.pip
- docs/source/changelog.rst
- pandas_gbq/_query.py
- pandas_gbq/gbq.py
- pandas_gbq/tests/test__query.py
- pandas_gbq/tests/test_gbq.py
- setup.py
There was a breaking change in 0.32.0 which changed the way
configuration for the query job gets loaded. Also, it added the
'description' field to the schema resource, so this change updates the
schema comparison logic to account for that.
Note: I've created this PR based on the code currently in `master` in the [google-cloud-bigquery repo](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery). The tests pass locally, but they won't pass anywhere else until google-cloud-bigquery 0.32.0 is released. I've added the **DO NOT MERGE** label to this PR for now.
Since pandas-gbq will be broken when google-cloud-bigquery does its next release, I think it would make sense to review this before than so it can be merged when everything is ready. Once it goes in, I can …
> BUG: Adapt to breaking change in google-cloud-bigquery 0.32.0.dev1

- docs/source/changelog.rst
Preparing for a release of 0.4.0.
FYI @jreback @parthea @maxim-lian I'll kick off a release today, since I would love for this to be out ahead of the next `google-cloud-bigquery` release https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5138 (the one with the breaking changes in the query configuration)
> DOC: Changelog for 0.4.0

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/tests/test_gbq.py
Closes #157 
(Assumes https://github.com/pandas-dev/pandas/pull/20564 will go in before Pandas 0.23.0 release)
/cc @craigcitro
> BUG: only show verbose warning for new pandas versions.

- .gitignore
- .travis.yml
- ci/requirements-3.5-0.18.1.pip
- ci/requirements-3.6-0.20.1.conda
- ci/requirements-3.6-MASTER.pip
- docs/source/changelog.rst
- docs/source/contributing.rst
- nox.py
- pandas_gbq/tests/test__query.py
- requirements-dev.txt
I couldn't actually reproduce the test failures introduced in https://github.com/pydata/pandas-gbq/pull/158 locally. My hope is that by using `nox` (like `tox`, but configurable via Python code) the more isolated environments will fix whatever error with mocks we're getting.
A step towards https://github.com/pydata/pandas-gbq/issues/52.
> TST: use nox for testing

- docs/source/contributing.rst
> CLN: update test paths in contributing guide

- .travis.yml
- ci/requirements-3.6-0.20.1.conda
- tests/unit/test_gbq.py
> TST: add mocked job_id for google-cloud-bigquery 0.29

- .travis.yml
My local tests seem to show that https://github.com/conda-forge/google-cloud-bigquery-feedstock/issues/10 has been resolved with the latest release of Miniconda (most recent
update was on 2018-05-02).
Travis build with credentials running at https://travis-ci.org/tswast/pandas-gbq/builds/374998229
> TST: use latest version of miniconda on Travis

- pandas_gbq/gbq.py
- tests/system.py
Now that load jobs are used, no sleep is required when replacing a table.
Tests with credentials running at https://travis-ci.org/tswast/pandas-gbq/builds/375003060
> CLN: remove workaround for streaming delays.

- pandas_gbq/auth.py
- tests/data/dummy_key.json
- tests/unit/test_auth.py
Tests (actual auth mocked out):
* Using private key with contents.
* Using private key with path.
* Using default credentials.
* Using cached user credentials.
Also, since I found it a little hard to debug the private key tests, update the error message with a little more information about what kind of credentials it thinks `private_key` is.
Closes #49
> TST: Add unit tests for pandas_gbq.auth.get_credentials().

- docs/source/changelog.rst
- docs/source/reading.rst
- docs/source/writing.rst
- pandas_gbq/gbq.py
* Update changelog with all changes since 0.4.1.
* Address warnings when building the docs due to mis-formed links.
* Removes some old references to streaming, which are no longer
relevant.
FYI: @aktech @maxim-lian Thanks to your contributions to this release.
> DOC: Prepare for 0.5.0 release

- docs/source/changelog.rst
Uses [Sphinx syntax for cross-reference labels](https://stackoverflow.com/a/19543591/101923).
> Add anchor links to versions in the changelog

- docs/source/changelog.rst
- pandas_gbq/load.py
- tests/unit/test_load.py
Based on issue #192.
The `load.py` module's `encode_chunk()` function writes to a local CSV buffer using Pandas' `to_csv()` function, which has a [known issue](https://stackoverflow.com/questions/12877189/float64-with-pandas-to-csv) regarding added significant figures on some operating systems. This can cause numerical overflow when loading the data into BigQuery.
This PR adds the `float_format='%.15g'` parameter to the `to_csv()` call.
This section provides a bit more detail behind the `%.15g` float format.
As per the Python 3 string format [documentation](https://docs.python.org/3.6/library/string.html#formatspec), the `g` (general) format acts as such:
> For a given precision p >= 1, this rounds the number to p significant digits and then formats the result in either fixed-point format …
> Use general float format when writing to CSV buffer to prevent numerical overload

- .travis.yml
- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
- tests/unit/test_gbq.py
Towards issue #195 
CC @RafaelAMello
> CLN: Warn that default dialect is changing to "standard"

- docs/source/changelog.rst
- pandas_gbq/gbq.py
Now we have clustering, we're looking at running more shorter queries. This PR reduces the volume of logs in INFO, particularly for short queries. 
Existing output:
```
2018-08-24 18:32:43,618 - pandas_gbq.gbq - INFO - Requesting query... 
2018-08-24 18:32:44,068 - pandas_gbq.gbq - INFO - ok.
Query running...
2018-08-24 18:32:44,073 - pandas_gbq.gbq - INFO - Job ID: d2c20d3f-97d3-44f8-b1be-ee8b10ec2818
Query running...
2018-08-24 18:32:44,700 - pandas_gbq.gbq - INFO - Got 1 rows.
2018-08-24 18:32:44,725 - pandas_gbq.gbq - INFO - Total time taken 1.11 s.
Finished at 2018-08-24 18:32:44.
```
New output for queries < 7s:
```
Query running...
Query running...
```
(it's repeated because we send an additional query, as per https://github.com/pydata/pandas-gbq/issues/198)
New output for queries …
> Reduce verbosity of logging

- docs/source/changelog.rst
- pandas_gbq/auth.py
- pandas_gbq/gbq.py
- tests/system/test_auth.py
- tests/unit/test_auth.py
- tests/unit/test_gbq.py
Don't do a query read when all you need to write is write credentials.
Closes https://github.com/pydata/pandas-gbq/issues/202
> [BUG] skip _try_credentials check for to_gbq

- pandas_gbq/auth.py
If the credentials on disk are invalid, then `get_user_credentials()` may fail
before it can fetch fresh credentials.
Noticed first and fixed in pydata-google-auth package in
https://github.com/pydata/pydata-google-auth/commit/7ce7f3f822fbaea7cc73878f52c61f8b38109f36
Note about pydata-google-auth: eventually I'd like to move pandas-gbq
to use that package for auth, but since I'm not sure when I'll have that
package ready, I'm patching pandas-gbq, too.
> [BUG] Don't load credentials from disk if reauth is True

- docs/source/changelog.rst
- pandas_gbq/gbq.py
ref https://github.com/pydata/pandas-gbq/pull/201#issuecomment-420828542
> Even quieter logging for short queries

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
Most tests only use a single dataset, so it doesn't make sense to list
datasets in the clean-up method.  Also, listing datasets is
eventually-consistent, so avoiding listing when it isn't necessary makes
the tests less flaky.
Removes unused _Dataset.tables() and _Dataset.datasets() methods.
Closes https://github.com/pydata/pandas-gbq/issues/215
> [TST] Avoid listing datasets and tables in system tests

- pandas_gbq/gbq.py
- tests/system/test_gbq.py
If dataset does not exist, it gets created in the correct location
Fixes issue 213: https://github.com/pydata/pandas-gbq/issues/213
> to_gbq respects location argument properly

- .gitignore
- docs/source/changelog.rst
- noxfile.py
- pandas_gbq/gbq.py
- pyproject.toml
- tests/system/test_gbq.py
- tests/unit/test_schema.py
Any date or time value in BQ can be converted to a pandas datetime value. As well as returning dataframes that don't requires as much post-processing, it also reducing the memory footprint of the returned object
I'm not sure whether this will cause any issues around timezones, and whether we need to parse those separately? (though this PR doesn't aim to enable timezone parsing, as long as there's no regression)
> Parse all date/time types

- docs/source/changelog.rst
- pandas_gbq/auth.py
Fixes the build errors on Travis, where GCE credentials are available but not actually useful.
Closes #226.
> ENH: Catch RefreshError in _try_credentials()

- docs/source/changelog.rst
- pandas_gbq/load.py
- tests/system/test_gbq.py
- tests/unit/test_load.py
Relates to #180.
I intended to include `\r\n` in the system test, but I found that something was stripping `\r` in the round trip:
```pytest
>       assert result_df.iloc[2,0] == "ij\r\nkl"
E       AssertionError: assert 'ij\nkl' == 'ij\r\nkl'
E         - ij
E         + ij
E         ?   +
E           kl
```
The unit test shows, I think, that we're sending the values correctly, so I didn't investigate further.
> Allow newlines in data passed to to_gbq()

- docs/source/changelog.rst
- docs/source/howto/authentication.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
Deprecates private_key parameter.
Note: I didn't actually add a deprecation warning message yet because I don't know which version of pandas this change will get added to.
Towards #161
> ENH: Add credentials argument to read_gbq and to_gbq.

- .circleci/config.yml
- .gitignore
- ci/config_auth.sh
- ci/requirements-2.7-0.19.2.pip
- ci/requirements-3.5-0.18.1.pip
- ci/requirements-3.6-MASTER.pip
- ci/run_conda.sh
- ci/run_pip.sh
- ci/run_tests.sh
- docs/source/contributing.rst
- tests/system/test_auth.py
Use CircleCI for testing pandas-gbq. This configuration uses the
canonical Python and miniconda3 Docker images to reduce problems caused
by a unique configuration.
Also:
* Re-enables conda tests.
* Adds Python 3.7 tests.
**Edit:** Conda build still fails https://github.com/pydata/pandas-gbq/issues/189
Closes https://github.com/pydata/pandas-gbq/issues/228 https://github.com/pydata/pandas-gbq/issues/197
> TST: configure CircleCI

- docs/source/intro.rst
- docs/source/reading.rst
- docs/source/tables.rst
- docs/source/writing.rst
Pointed out by @msegado https://github.com/pydata/pandas-gbq/issues/174#issuecomment-437252820
> remove old docs

- pandas_gbq/gbq.py
- tests/unit/test_context.py
This will allow people to revert the dialect to legacy SQL when we
switch the default or use standard SQL as the default earlier.
Towards #195.
> ENH: Add pandas_gbq.context.dialect to modify default dialect

- docs/source/api.rst
- docs/source/changelog.rst
- docs/source/contributing.rst
- docs/source/howto/authentication.rst
- pandas_gbq/gbq.py
- setup.py
* Update changelog.
* Add Python 3.7 to supported versions in the package.
* Fix docstrings in new Context class to match pandas-style.
* Document new context class in authentication and API docs.
Note: I put Monday as the date that I'll actually pull the trigger to push to PyPI because it's probably not the kindest thing to release late on a Friday.
> Release 0.8.0

- docs/source/howto/authentication.rst
- pandas_gbq/gbq.py
- tests/unit/test_gbq.py
The argument was already deprecated in the function docs. This commit
adds a warning when using pandas 0.24 or greater (the first version to
include the credentials argument).
Towards #161 
Also, I add imports in the auth how-to guide towards #239 since I link to
that how-to in the warning text.
> ENH: deprecate private_key argument

- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/howto/authentication.rst
- docs/source/install.rst
- pandas_gbq/auth.py
- pandas_gbq/gbq.py
- setup.py
- tests/system/test_auth.py
- tests/unit/test_auth.py
- tests/unit/test_gbq.py
Only private_key logic and customized path for credentials cache remain.
At some point in the future private_key logic will be removed, as that
parameter is deprecated in favor of the credentials argument.
Also removes the _try_credentials logic, as that slows down the
authentication process and is largely unnecessary now that credentials
can be explicitly created and supplied via the credentials argument.
Closes #161
> CLN: use pydata-google-auth for auth flow

- pandas_gbq/gbq.py
- tests/unit/test_gbq.py
Removes the warning when a SQL dialect is unspecified.
Closes #195
> ENH: Use standard SQL as default.

- benchmark/README.md
- benchmark/read_gbq_large_results.py
- benchmark/read_gbq_small_results.py
- ci/requirements-2.7.pip
- ci/requirements-3.5.pip
- ci/requirements-3.6-0.20.1.conda
- ci/run_conda.sh
- docs/source/changelog.rst
- pandas_gbq/gbq.py
- setup.py
- tests/system/test_gbq.py
- tests/unit/test_gbq.py
This allows us to remove logic for parsing the schema and align with
google-cloud-bigquery.
Towards #149 
Note, I ran the profiler before and after. For some reason I got about an extra 20 seconds with this versus before (331 before, 352 after). I can't figure out why that would be since in both cases we're just looping over all the rows and constructing a dataframe. Maybe it was just a fluke of my work WiFi network?
In either case, this change will help us with https://github.com/pydata/pandas-gbq/issues/242 once I release the next version of `google-cloud-bigquery`. It'll also help us with https://github.com/pydata/pandas-gbq/issues/133 whenever the mystery faster API launches.
> CLN: Use `to_dataframe` to download query results.

- docs/source/intro.rst
The import of `sys` isn't necessary in the logging example, as `sys.stdout` is the default stream for `StreamHandler`. In the interest of keeping examples as minimal as possible I would suggest to remove references to `sys.stdout` and leave that to the `logging` documentation.
> Remove import sys in logging documentation example

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/schema.py
- tests/unit/test_schema.py
This PR:
* Adds a function to `pandas_gbq.schema`, `update_schema` which takes and old schema and a new one, updating any existing fields and adding any new ones
* Generates the default schema using `schema.generate_bq_schema` for every DataFrame passed to `to_gbq`, and if a `table_schema` is passed, this schema is used to update the generated schema. This way custom provided fields in `table_schema` are added, and missing fields fall back to the generated defaults.
This is the functionality requested in #218
> ENH: Allow partial table schema in to_gbq() table_schema (#218)

- pandas_gbq/gbq.py
- tests/system/test_gbq.py
No reason to run a load job if there is no data to load. This avoids a
"Empty schema specified for the load job." error when the DataFrame also
contains no columns.
Closes #237.
> BUG: avoid load jobs for empty dataframes

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/unit/test_gbq.py
it seems a bit redundant to have to specify both in the common case where the service account is used for a single project
> read project_id from credentials if available

- docs/source/howto/authentication.rst
- docs/source/index.rst
- docs/source/privacy.rst
This is required for verification of the OAuth 2.0 consent screen.
> DOC: Add privacy policy for pandas GBQ

- ci/requirements-2.7.pip
- docs/source/changelog.rst
- setup.py
- tests/system/test_gbq.py
This should make checking for expected dtypes more robust.
An attempt at tackling https://github.com/pydata/pandas-gbq/issues/261. Though I would love to be more precise about whether a `datetime64` comes back as timezone aware or not, the fact that the behavior changed in pandas 0.24.x makes such a precise test challenging.
> TST: Use pandas.api.types functions for dtypes checks

- docs/source/changelog.rst
- pandas_gbq/auth.py
These auth credentials for the browser authentication flow belong to the
pandas-gbq-auth GCP project. The reason for the fresh project is that
this allows us to explicitly enable APIs needed for new functionality,
such as the BigQuery Storage API.
> CLN: Update the authentication credentials.

- docs/source/changelog.rst
- docs/source/reading.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
- tests/unit/test_gbq.py
Adds a table documenting the current behavior, including that pandas 0.24.0 stores as time zone aware dtype and earlier versions store naive. I could not figure out how to make 0.24.0+ store as a naive dtype (https://github.com/pydata/pandas-gbq/issues/261), nor could I figure out how to make earlier versions use time zone aware (https://github.com/pydata/pandas-gbq/pull/263)
> ENH: Use tz-aware dtype for timestamp columns

- docs/source/changelog.rst
- docs/source/reading.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
The BigQuery Storage API provides a way to read query results quickly
(and using multiple threads). It only works with large query results
(~125 MB), but as of 1.11.1, the google-cloud-bigquery library can
fallback to the BigQuery API to download results when a request to the
BigQuery Storage API fails.
As this API can increase costs (and may not be enabled on the user's
project), this option is disabled by default.
> ENH: Add use_bqstorage_api option to read_gbq

- .circleci/config.yml
- MANIFEST.in
- ci/requirements-2.7.pip
- docs/source/changelog.rst
- noxfile.py
- pandas_gbq/auth.py
- release-procedure.md
- setup.py
- tests/system/test_auth.py
- tests/system/test_gbq.py
- tests/unit/conftest.py
- tests/unit/test_auth.py
- tests/unit/test_context.py
- tests/unit/test_gbq.py
The 0.10.0 package will be the latest version to support Python 2. This
aligns pandas-gbq with pandas, which dropped support for Python 2 at the
end of 2019.
Closes #268
> CLN: Drop support for Python 2.

- pandas_gbq/gbq.py
- pandas_gbq/load.py
- pandas_gbq/schema.py
- tests/unit/test_gbq.py
Fixes #277.
If any dictionary entry in the `table_schema` arg did
not contain a "mode" key, a mode="NULLABLE" kv pair
would be created; because `schema.update_schema()`
returns an object with references to its mutable input,
this allows the argument to ultimately be modified
by the function rather than the caller.
This pattern was used in both gbq.py and load.py,
so it was refactored into a helper function in
schema.py, which now returns a modified *copy*.
Deepcopy is used because the input is a list of
dictionaries, so a shallow copy would be insufficient.
> Ensure table_schema arg is not modified inplace

- tests/system/test_gbq.py
- tests/unit/test_gbq.py
Tests were failing because the `str` method for the context returned by
`pytest.raises` no longer prints the contained exception. Instead, use
`match=regex_value` to check for the desired error message.
> TST: Fix pytest.raises usage for latest pytest. Fix warnings in tests.

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
If a there are no rows, the default dtype is used (which is now
float64, must previously have been object).
> BUG: Use object dtype for STRING, ARRAY, and STRUCT columns when there are zero rows.

- ci/requirements-3.6-0.20.1.conda
- ci/requirements-3.7-NIGHTLY.conda
- ci/requirements-3.7.pip
- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
- tests/unit/conftest.py
- tests/unit/test_auth.py
- tests/unit/test_gbq.py
Since this was a relatively new addition to the BigQuery client library,
only populate the user-agent for BigQuery when recent-enough versions of
google-cloud-bigquery and google-api-core are installed.
Closes #281.
> ENH: Add user-agent string when constructing BigQuery and BigQuery Storage API clients.

- docs/source/changelog.rst
- noxfile.py
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
- tests/unit/conftest.py
- tests/unit/test_gbq.py
This argument allows you to set a maximum number of rows
in the resulting dataframe. Set to 0 to ignore any results.
Created as draft because this PR needs:
Closes https://github.com/pydata/pandas-gbq/issues/102
> ENH: Add max_results argument to read_gbq.

- docs/source/howto/authentication.rst
The closing parenthesis is missing in the current code example, making copy/paste of the code failing.
> Missing parenthesis in code example

- ci/requirements-3.5.pip
- ci/requirements-3.6-0.20.1.conda
- docs/source/changelog.rst
- pandas_gbq/gbq.py
- setup.py
- tests/system/test_auth.py
- tests/unit/test_gbq.py
Version 1.11.0 was the first version to include a `progress_bar_type`
argument. https://googleapis.dev/python/bigquery/latest/changelog.html#id51
Closes #296
> FIX: update minimum google-cloud-bigquery version to 1.11.0

- docs/source/changelog.rst
- noxfile.py
- pandas_gbq/auth.py
- pandas_gbq/gbq.py
- pandas_gbq/load.py
- tests/system/test_auth.py
- tests/unit/test_auth.py
- tests/unit/test_gbq.py
The argument will be removed in pandas 1.0. https://github.com/pandas-dev/pandas/pull/30200
Closes #301.
> CLN: remove deprecated `private_key` auth logic

- ci/requirements-3.5.pip
- ci/run_conda.sh
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
Also, allow jobTimeoutMs, as that is the name for the backend parameter.
> TST: use larger query for timeout test

- ci/requirements-3.5.pip
- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/timestamp.py
- tests/system/conftest.py
- tests/system/test_gbq.py
- tests/system/test_read_gbq_with_bqstorage.py
- tests/unit/test_timestamp.py
Closes #299
**Also:**
* Refactors timestamp helpers to their own file to help reduce the size of the gbq module.
* Use `bigquery_storage_v1beta1` module to avoid breaking when `bigquery_storage_v1beta2` is released with breaking changes.
**TODO:**
> BUG: fix AttributeError with BQ Storage API to download empty results

- docs/source/changelog.rst
- setup.py
This way necessary version ranges for transitive dependencies such as
google-cloud-bigquery-storage and pyarrow are included in the
installation.
Towards #329
> BUG: include needed "extras" from google-cloud-bigquery package

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
- tests/unit/test_gbq.py
Use this argument to override the default ``dtype`` for a particular column in
the query results. For example, this can be used to select nullable integer
columns as the ``Int64`` nullable integer pandas extension type.
df = gbq.read_gbq(
"SELECT CAST(NULL AS INT64) AS null_integer",
dtypes={"null_integer": "Int64"},
)
Closes #332
Closes #242
> ENH: add dtypes argument to read_gbq

- conftest.py
- docs/source/changelog.rst
- pandas_gbq/exceptions.py
- pandas_gbq/gbq.py
- setup.py
- tests/system/conftest.py
- tests/system/test_read_gbq_with_bqstorage.py
- tests/unit/test_gbq.py
Removes references to BQ Storage API beta endpoint.
Closes #329
> BUG: update library to support google-cloud-bigquery 2.0

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
Adds tests for TIME and DATE datatypes.
Closes #328
> BUG: use object dtype for TIME columns

- docs/source/changelog.rst
- pandas_gbq/gbq.py
- pandas_gbq/load.py
- tests/unit/test_gbq.py
After merging this PR, it will be possible to write data into tables stored in a different project ID than the client project when calling the function `to_gbq()`.
Note that in the python-bigquery API from Google you can do this by using the method `load_table_from_dataframe` ([link](https://github.com/googleapis/python-bigquery/blob/master/google/cloud/bigquery/client.py#L1780)) which receives as input a `TableReference` object ([link](https://github.com/googleapis/python-bigquery/blob/master/google/cloud/bigquery/table.py#L119)) (with a `project_id`, a `dataset_id` and a `table_id`), being however called from a `client` running jobs in a separate `project_id`.
I think this enhancement will be very useful in situations where splitting the costs among projects is important, while …
> ENH: add project id to destination table in to_gbq()

- ci/constraints-3.7.pip
- pandas_gbq/gbq.py
- tests/system/test_gbq.py
While updating uses, I noticed `schema()` and `verify_schema()` are only used in tests. Moved them to the corresponding test file.
Closes #312
> FIX: remove references to deprecated client.dataset method

- docs/source/changelog.rst
- setup.py
- [N/A] tests added / passed
Closes #343
> FIX: exclude google-cloud-bigquery==2.4.x from dependencies

- samples/snippets/requirements.txt
Periodic tests were failing due to a missing reference to `pandas-gbq` in the `samples/snippets/requirements.txt` file.
This update remedies that issue.
Fixes #574 🦕
> fix: updates requirements.txt to fix failing tests due to missing req
